# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/question_aval',
                'doc_host': 'https://bcnbru.github.io',
                'git_url': 'https://github.com/bcnbru/question_aval',
                'lib_path': 'question_aval'},
  'syms': {'question_aval.core': {'question_aval.core.foo': ('core.html#foo', 'question_aval/core.py')}}}
